language: python 

python: 
  - "3.6"

services: 
  - postgresql

addons:
  postgresql: "9.6"

install: 
  - pip install -r requirements.txt
  - pip install coveralls

before_script: 
  - psql -c "CREATE DATABASE zurutours;" -U postgres

script:
  - cd zurutoursapi
  - coverage run --source="." manage.py test
  - coverage report

after_success:
  - coveralls