# Generated by Django 2.1.7 on 2019-03-20 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0002_auto_20190319_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('tickets', models.IntegerField(verbose_name='Number of people booked')),
                ('pp_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Booking Cost Per Person')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
        ),
    ]
