# Generated by Django 2.1.7 on 2019-03-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
