# Generated by Django 2.1.7 on 2019-03-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('end_datetime', models.DateTimeField(verbose_name='End Date')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date')),
                ('capacity', models.IntegerField(max_length=3, verbose_name='Tour Capacity')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Tour Cost')),
                ('title', models.CharField(max_length=60, verbose_name='Tour Title')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
