language: python

python:
  - "3.6"

install:
  - pipenv install

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database zurutours;' -U postgres

script:
  - cd zurutoursapi
  - python manage.py test